services:
  backend:
    build: ./backend/
    container_name: tos-backend
    ports:
      - 8000:8000
    environment:
      - NEO4J_URL=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=strongpasswd
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:5.25
    container_name: tos-neo4j
    restart: always
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/strongpasswd
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:
